class ApiUrl {
  /// Base URL
  // static const baseUrl =
  //     "https://testsite.myserviceforce.com/cec/Services/DeviceService.asmx";
  static const baseUrl =
      "https://mxp.myserviceforce.com/cec/Services/DeviceService.asmx";
  // "https://jobs-msschedules.myserviceforce.com/Services/DeviceService.asmx";

  static const paymentBaseUrl =
      "https://paymentportal.xceleran.com/webterminal/Clearent/AppCCPayment_CL.aspx";
  // static const paymentBaseUrl =
  //     "https://dev-services.myserviceforce.com/webterminal/Clearent/AppCCPayment_CL.aspx";
  static const fileBaseUrl =
      "https://mxp.myserviceforce.com/cec/Services/FSMFiles";
  static const imageBaseUrl = "https://mxp.myserviceforce.com/fsm/FSMPictures";
  static const paymentSignatureBaseUrl =
      "https://mxp.myserviceforce.com/cec/Services";
  static const login = "$baseUrl/VerifyUser";
  static const getAppointment = "$baseUrl/GetAppointmentList";
  static const getInvoiceList = "$baseUrl/GetAppointmentListCustomerSiteWise";
  static const getAttachedForms = "$baseUrl/GetAppointmentListWithForms";
  static const updateAppointment = "$baseUrl/UpdateAppointment";
  static const sendCustomerSMS = "$baseUrl/SendCustomerSMS";
  static const getCustomer = "$baseUrl/GetCustomerList";
  static const getInvoices = "$baseUrl/GetInvoiceList";
  static const getTicketStatusList = "$baseUrl/GetTicketStatusList";
  static const getAppointmentStatusList = "$baseUrl/GetStatusList";
  static const getTax = "$baseUrl/GetTaxList";
  static const xpayLink = "$baseUrl/GenerateXPayLink";
  static const getItems = "$baseUrl/GetAllItemList";
  static const getItemGroups = "$baseUrl/GetItemGroups";
  static const getItemGroupById = "$baseUrl/GetItemGroupById";

  // Bundle endpoints (note: GetItemsByBundleId is spelled without 't' -> GeItemsByBundleId)
  static const getBundles = "$baseUrl/GetBundles";
  static const getItemsByBundleId = "$baseUrl/GeItemsByBundleId";
  static const saveBundle = "$baseUrl/SaveBundle";
  static const deleteBundle = "$baseUrl/DeleteBundle";

  static const getInvoiceName = "$baseUrl/GetAutoGeneratedInvoice";
  static const createInvoice = "$baseUrl/CreateInvoice";
  static const editInvoice = "$baseUrl/EditInvoice";
  static const sendEmail = "$baseUrl/SendHtmlFormattedEmail";
  static const makePayment = "$baseUrl/AddPayment";
  static const saveSignature = "$baseUrl/SaveSignature";
  static const saveSignatureForPayment = "$baseUrl/SaveSignatureForPayment";
  static const emailAutofill = "$baseUrl/GetAutoFillValuesForEmail";
  static const convertEST = "$baseUrl/ConvertEstimateToInvoice";
  // static const saveImageUrl = "$baseUrl/SaveImageForCSL";
  static const saveImageUrl = "$baseUrl/SavePictures";
  // static const getImageListUrl = "$baseUrl/GetImageForCSL";
  static const getImageListUrl = "$baseUrl/GetPictures";
  static const saveFilesUrl = "$baseUrl/SaveFiles";
  static const getFilesUrl = "$baseUrl/GetFiles";
  static const saveFormUrl = "$baseUrl/SaveFormTemplate";
  static const updateFormUrl = "$baseUrl/UpdateFormTemplate";
  static const assignFormUrl = "$baseUrl/AssignForm";
  static const getAllTagUrl = "$baseUrl/GetAllTags";
  static const saveTagUrl = "$baseUrl/SaveTag";
  static const updateTagUrl = "$baseUrl/UpdateTag";
  static const saveNoteUrl = "$baseUrl/SaveNote";
  static const updateNoteUrl = "$baseUrl/UpdateNote";
  static const getAllNotesUrl = "$baseUrl/GetAllNote";
  static const saveEquipmentUrl = "$baseUrl/SaveEquipment";
  static const updateEquipmentUrl = "$baseUrl/UpdateEquipment";
  static const getEquipmentUrl = "$baseUrl/GetEquipment";
  static const getEquipmentTypeUrl = "$baseUrl/GetEquipmentTypes";
  static const getQBOLocationsUrl = "$baseUrl/GetQBOLocations";
  static const getQBOClassesUrl = "$baseUrl/GetQBOClasses";
  static const getCustomFieldsUrl = "$baseUrl/GetAllCustomFields";
  static const saveCustomFieldUrl = "$baseUrl/SaveCustomFeild";
  static const getAttachedCustomFieldsUrl =
      "$baseUrl/GetAllAppointmentCustomFields";
  static const saveAttachedCustomFieldsUrl =
      "$baseUrl/SaveAppointmentCustomFields";
  static const generateTuaPaymentLink = "$baseUrl/GenerateTuaPaymentLink";
  static const getCustomerSitesUrl = "$baseUrl/GetCustomerSites";
  static const getTimeSlotListUrl = "$baseUrl/GetTimeSlotList";
  static const getNextAppointmentNumberUrl = "$baseUrl/GetNextAppointmentNumber";
  static const getServiceTypeListUrl = "$baseUrl/GetServiceTypeList";
  static const getResourceListUrl = "$baseUrl/GetResourceList";

  // Forms API endpoints
  static const getAllForms = "$baseUrl/GetAllFormTemplates";
  static const assignFormsToAppointment = "$baseUrl/AssignForm";
  static const getAppointmentForms = "$baseUrl/GetAppointmentForms";

  //forms API endpoints

  /// Base URL for FaProSync API
  static const String baseTestUrl = "https://testsite.myserviceforce.com/fsm";

  static const String baseLiveUrl = "https://mxp.myserviceforce.com/fsm";

  /// Base URL for PDF files
  static const String pdfBaseUrl =
      // "https://testsite.myserviceforce.com";
      "https://mxp.myserviceforce.com";

  /// Get current base URL
  static String get currentBaseUrl => baseLiveUrl;

  /// Get current PDF base URL
  static String get currentPdfBaseUrl => baseLiveUrl;

  /// API Key for FaProSync
  static const String apiKey = "fapro_a8f3k29dm4c7p1r6w9q2x5y8b3n7t1v4z6h0j2l5";

  // ============== BUILD URL METHODS ==============

  /// Build poll URL: GET /FaProSync.ashx?op=poll&companyId={X}&resourceId={Y}
  static String pollUrl(String companyId, String resourceId) {
    return "$currentBaseUrl/FaProSync.ashx?op=poll&companyId=$companyId&resourceId=$resourceId";
  }

  /// Build ack URL: POST /FaProSync.ashx?op=ack
  static String get ackUrl => "$currentBaseUrl/FaProSync.ashx?op=ack";

  /// Build submit URL: POST /FaProSync.ashx?op=submit
  static String get submitUrl => "$currentBaseUrl/FaProSync.ashx?op=submit";

  /// Build PDF download URL
  static String pdfDownloadUrl(String relativePath) {
    final cleanPath = relativePath.startsWith('/')
        ? relativePath.substring(1)
        : relativePath;
    return "$currentPdfBaseUrl$cleanPath";
  }

  /// Build stamped PDF URL
  static String stampedPdfUrl(String relativePath) {
    return pdfDownloadUrl(relativePath);
  }

  /// Build get template URL: GET /FaProSync.ashx?op=gettemplate&companyId={X}&templateId={Y}
  static String getTemplateUrl(String companyId, int templateId) {
    return "$currentBaseUrl/FaProSync.ashx?op=gettemplate&companyId=$companyId&templateId=$templateId";
  }

  /// Build get template PDF URL: GET /FaProSync.ashx?op=gettemplatepdf&companyId={X}&templateId={Y}
  static String getTemplatePdfUrl(String companyId, int templateId) {
    return "$currentBaseUrl/FaProSync.ashx?op=gettemplatepdf&companyId=$companyId&templateId=$templateId";
  }

  /// Build get response URL: GET /FaProSync.ashx?op=getResponse&companyId={X}&formResponseId={Y}
  static String getResponseUrl(String companyId, int formResponseId) {
    return "$currentBaseUrl/FaProSync.ashx?op=getResponse&companyId=$companyId&formResponseId=$formResponseId";
  }

  /// Build get response by natural key URL: GET /FaProSync.ashx?op=getResponse&companyId={X}&templateId={Y}&appointmentId={Z}&customerId={W}
  static String getResponseByNaturalKeyUrl({
    required String companyId,
    required int templateId,
    required String appointmentId,
    required String customerId,
  }) {
    return "$currentBaseUrl/FaProSync.ashx?op=getResponse&companyId=$companyId&templateId=$templateId&appointmentId=$appointmentId&customerId=$customerId";
  }

  // ============== HEADERS ==============

  /// Authentication header with API key
  static Map<String, String> get authHeaders => {"X-Api-Key": apiKey};

  /// JSON content type headers with auth
  static Map<String, String> get jsonHeaders => {
    "Content-Type": "application/json",
    ...authHeaders,
  };

  // ============== FaProMobile API ==============

  /// Base URL for FaProMobile API
  static const String faProMobileBaseUrl =
      "https://mxp.myserviceforce.com/fsm/FaProMobile.ashx";

  /// Build FaProMobile URL with query parameters
  static String buildFaProMobileUrl({
    required String resource,
    required String operation,
    required String companyId,
    Map<String, String>? extraParams,
  }) {
    final uri = Uri.parse(faProMobileBaseUrl);
    final params = {
      'resource': resource,
      'op': operation,
      'companyId': companyId,
      ...?extraParams,
    };
    return uri.replace(queryParameters: params).toString();
  }

  /// FaProMobile authentication header with API key
  static Map<String, String> get faProMobileAuthHeaders => {
    "X-Api-Key": apiKey,
  };

  /// FaProMobile JSON content type headers with auth
  static Map<String, String> get faProMobileJsonHeaders => {
    "Content-Type": "application/json",
    "X-Api-Key": apiKey,
  };
}

// Alias for consistency with existing code
typedef ApiUrls = ApiUrl;
