class ApiUrl {
  /// Base URL
  static const baseUrl =
      "https://testsite.myserviceforce.com/cec/Services/DeviceService.asmx";
  // static const baseUrl =
  //     "https://jobs-msschedules.myserviceforce.com/Services/DeviceService.asmx";
  static const login = "$baseUrl/VerifyUser";
  static const getAppointment = "$baseUrl/GetAppointmentList";
  static const getAttachedForms = "$baseUrl/GetAppointmentListWithForms";
  static const updateAppointment = "$baseUrl/UpdateAppointment";
  static const getCustomer = "$baseUrl/GetCustomerList";
  static const getInvoices = "$baseUrl/GetInvoiceList";
  static const getTicketStatusList = "$baseUrl/GetTicketStatusList";
  static const getAppointmentStatusList = "$baseUrl/GetStatusList";
  static const getTax = "$baseUrl/GetTaxList";
  static const xpayLink = "$baseUrl/GenerateXPayLink";
  static const getItems = "$baseUrl/GetAllItemList";
  static const getInvoiceName = "$baseUrl/GetAutoGeneratedInvoice";
  static const createInvoice = "$baseUrl/CreateInvoice";
  static const editInvoice = "$baseUrl/EditInvoice";
  static const sendEmail = "$baseUrl/SendHtmlFormattedEmail";
  static const makePayment = "$baseUrl/AddPayment";
  static const emailAutofill = "$baseUrl/GetAutoFillValuesForEmail";
  static const convertEST = "$baseUrl/ConvertEstimateToInvoice";
  static const getFormTypeUrl = "$baseUrl/GetAllFormTemplates";
  static const saveImageUrl = "$baseUrl/SaveImageForCSL";
  static const getImageListUrl = "$baseUrl/GetImageForCSL";
  static const saveFormUrl = "$baseUrl/SaveFormTemplate";
  static const updateFormUrl = "$baseUrl/UpdateFormTemplate";
  static const assignFormUrl = "$baseUrl/AssignForm";
  static const getAllTagUrl = "$baseUrl/GetAllTags";
  static const saveTagUrl = "$baseUrl/SaveTag";
  static const updateTagUrl = "$baseUrl/UpdateTag";
  static const saveNoteUrl = "$baseUrl/SaveNote";
  static const updateNoteUrl = "$baseUrl/UpdateNote";
  static const getAllNotesUrl = "$baseUrl/GetAllNote";
  static const getQBOLocationsUrl = "$baseUrl/GetQBOLocations";
  static const getQBOClassesUrl = "$baseUrl/GetQBOClasses";
  static const getCustomFieldsUrl = "$baseUrl/GetAllCustomFields";
  static const saveCustomFieldUrl = "$baseUrl/SaveCustomFeild";
}
